import React from "react";

export default function StepsExxatComAdminTenantApps1440WDefault() {
  return (
    <div className="min-h-dvh w-full overflow-x-hidden bg-[#f8f8f8] h2d-screen-root" style={{ minHeight: '900px' }}>
      <div className="mx-auto w-full max-w-[1440px] h2d-screen-inner" style={{ minHeight: '900px' }}>
      <html style={{width: '100%', borderColor: 'rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '10px', letterSpacing: '-0.1px', lineHeight: '14px', minHeight: '900px', outlineColor: 'rgb(0, 0, 0)', outlineWidth: '3px', overflow: 'visible', overflowX: 'visible', overflowY: 'visible', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
        <body className="ng-tns-0-0 theme-blue-light" style={{width: '100%', backgroundColor: 'rgb(248, 248, 248)', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minHeight: '900px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', overflow: 'visible', overflowX: 'visible', overflowY: 'visible', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
          <v4-app-root style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
            <vertical-layout-1 className="ng-tns-c3472566873-1 ng-star-inserted" style={{width: '100%', height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
              <div id="main" className="ng-tns-c3472566873-1" style={{width: '100%', height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', zIndex: '1', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                <exxat-announcements className="ng-tns-c3472566873-1 ng-tns-c1985112821-2 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
                <div id="container-1" className="container ng-tns-c3472566873-1" style={{width: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                  <div id="container-2" className="container ng-tns-c3472566873-1" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                    <div id="container-3" className="container ng-tns-c3472566873-1" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                      <content id="app_main_content" className="ng-tns-c3472566873-1" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', zIndex: '1', order: '0', flexGrow: '1', flexShrink: '0', opacity: '1'}}>
                        <router-outlet className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
                        <tenant-navigations className="ng-star-inserted" style={{width: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minWidth: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '0', opacity: '1'}}>
                          <div id="dashboard-screen-container" className="page-layout simple full-width-page full-width h-100-p" style={{width: '100%', height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minWidth: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', overflow: 'hidden', overflowX: 'hidden', overflowY: 'hidden', padding: '16px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '0', opacity: '1'}}>
                            <div className="mt-xs-12" style={{alignContent: 'flex-start', alignItems: 'flex-start', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                              <div className="mb-12 fuse-white-bg border-radius-4 dash_logo_container ng-star-inserted" style={{marginBottom: '12px', alignContent: 'center', alignItems: 'center', backgroundColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '4px', borderBottomRightRadius: '4px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 12px', maxHeight: '96px', minWidth: 'fit-content', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                <img alt="Exxat Logo" src="/prism-demo-screens/assets/asset_956cce07.png" className="dash_logo" style={{borderBottomLeftRadius: '4px', borderBottomRightRadius: '4px', borderColor: 'rgb(255, 255, 255)', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', borderWidth: '4px', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxHeight: '96px', maxWidth: '350px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', overflow: 'clip', overflowX: 'clip', overflowY: 'clip', verticalAlign: 'top', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
                              </div>
                              <div className="mb-12 ml-gt-sm-16 w-100-p" style={{width: '100%', marginLeft: '16px', marginBottom: '12px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 12px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                <div className="info-box info info-height" style={{backgroundColor: 'rgb(179, 229, 252)', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.12)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderWidth: '1px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxHeight: '96px', minHeight: '96px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '8px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                  <div className="font-weight-600" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                    <span style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Say Hello to Prism!</span>
                                    </span>
                                  </div>
                                  <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                    <span id="important_message" className="truncate-with-hover-gt-sm" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flow-root', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', overflow: 'hidden', overflowX: 'hidden', overflowY: 'hidden', textOverflow: 'ellipsis', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>We are thrilled to announce that “Version 4” is now </span>
                                      <a style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', textDecoration: 'underline', textDecorationLine: 'underline', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Prism!</span>
                                      </a>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}> Prism brings it all together and provides you with access to every feature Exxat has to offer all in one</span>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>place - start exploring today. Our </span>
                                      <a style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', textDecoration: 'underline', textDecorationLine: 'underline', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Help Center</span>
                                      </a>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>, </span>
                                      <a style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', textDecoration: 'underline', textDecorationLine: 'underline', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>YouTube</span>
                                      </a>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}> channel and </span>
                                      <a style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', textDecoration: 'underline', textDecorationLine: 'underline', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Support teams</span>
                                      </a>
                                      <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}> can help you along the way.</span>
                                    </span>
                                  </div>
                                </div>
                              </div>
                              <div className="h-64 mb-12 ml-gt-sm-16 fuse-white-bg border-radius-4 brand_logo_container" style={{height: '64px', marginLeft: '16px', marginBottom: '12px', alignContent: 'center', alignItems: 'center', backgroundColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '4px', borderBottomRightRadius: '4px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '4px', borderTopRightRadius: '4px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'center', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 12px 16px', maxHeight: '64px', maxWidth: '15%', minHeight: '64px', minWidth: '15%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                <img alt="EXXAT PRISM Logo" src="/prism-demo-screens/assets/asset_1d6b58d2.svg" className="brand_logo" style={{height: '75px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxWidth: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', overflow: 'clip', overflowX: 'clip', overflowY: 'clip', verticalAlign: 'top', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
                              </div>
                            </div>
                            <div className="center h-100-p" style={{height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                              <div className="content h-100-p ng-star-inserted" style={{height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                <div className="dashboard-screen-card-height pr-gt-sm-8 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '100%', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxWidth: '33.3333%', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '0px 8px 0px 0px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                  <mat-card className="mat-mdc-card mdc-card p-0 mb-lt-md-16 dashboard_card dashboard-screen-card-height pink-border ng-star-inserted" style={{backgroundColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgb(236, 38, 143)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderWidth: '1px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                    <div className="card_content p-16 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                      <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <div className="hover py-12 px-16 border-radius-8 cursor-pointer dashboard_nav_item ng-star-inserted" style={{alignContent: 'stretch', alignItems: 'stretch', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '12px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                          <div style={{alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <i className="fa-light fa-users pink-foreground s-24" style={{width: '24px', height: '24px', borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline-block', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', minHeight: '24px', minWidth: '24px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span className="__h2d-remove-before __h2d-remove-after" style={{transformOrigin: '0px 0px', borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', textDecoration: 'rgb(228, 7, 125)', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                  <span style={{fontFamily: '\'Font Awesome 6 Pro Light\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}></span>
                                                </span>
                                              </i>
                                            </div>
                                            <div className="ml-16" style={{marginLeft: '16px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 0px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="font-weight-600 font-18 focus-outline-border text-underline pink-foreground ng-star-inserted" style={{borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '18px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '25.2px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>User Management</span>
                                              </span>
                                            </div>
                                          </div>
                                          <div className="mt-8" style={{marginTop: '8px', alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '8px 0px 0px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="dashboard_nav_item_desc" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Manage Users and Roles for your University</span>
                                              </span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <div className="hover py-12 px-16 border-radius-8 cursor-pointer dashboard_nav_item ng-star-inserted" style={{alignContent: 'stretch', alignItems: 'stretch', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '12px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                          <div style={{alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <i className="fa-chart-mixed fa-light pink-foreground s-24" style={{width: '24px', height: '24px', borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline-block', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', minHeight: '24px', minWidth: '24px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span className="__h2d-remove-before __h2d-remove-after" style={{transformOrigin: '0px 0px', borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', textDecoration: 'rgb(228, 7, 125)', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                  <span style={{fontFamily: '\'Font Awesome 6 Pro Light\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}></span>
                                                </span>
                                              </i>
                                            </div>
                                            <div className="ml-16" style={{marginLeft: '16px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 0px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="font-weight-600 font-18 focus-outline-border text-underline pink-foreground ng-star-inserted" style={{borderColor: 'rgb(228, 7, 125)', color: 'rgb(228, 7, 125)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '18px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '25.2px', outlineColor: 'rgb(228, 7, 125)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(228, 7, 125)', WebkitTextStrokeColor: 'rgb(228, 7, 125)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Program 360</span>
                                              </span>
                                            </div>
                                          </div>
                                          <div className="mt-8" style={{marginTop: '8px', alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '8px 0px 0px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="dashboard_nav_item_desc" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Get a snapshot of key metrics and performance trends of your</span>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>programs in one place</span>
                                              </span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </mat-card>
                                </div>
                                <div className="dashboard-screen-card-height pl-gt-sm-8 pr-gt-sm-8 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '100%', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxWidth: '33.3333%', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '0px 8px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                  <mat-card className="mat-mdc-card mdc-card p-0 mb-lt-md-16 dashboard_card dashboard-screen-card-height orange-border ng-star-inserted" style={{backgroundColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgb(245, 136, 54)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderWidth: '1px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                    <div className="card_content p-16 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                      <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <div className="hover py-12 px-16 border-radius-8 cursor-pointer dashboard_nav_item ng-star-inserted" style={{alignContent: 'stretch', alignItems: 'stretch', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '12px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                          <div style={{alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <i className="fa-file-invoice fa-light orange-foreground s-24" style={{width: '24px', height: '24px', borderColor: 'rgb(182, 95, 3)', color: 'rgb(182, 95, 3)', display: 'inline-block', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', minHeight: '24px', minWidth: '24px', outlineColor: 'rgb(182, 95, 3)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(182, 95, 3)', WebkitTextStrokeColor: 'rgb(182, 95, 3)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span className="__h2d-remove-before __h2d-remove-after" style={{transformOrigin: '0px 0px', borderColor: 'rgb(182, 95, 3)', color: 'rgb(182, 95, 3)', display: 'inline', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', outlineColor: 'rgb(182, 95, 3)', outlineWidth: '3px', textDecoration: 'rgb(182, 95, 3)', WebkitTextFillColor: 'rgb(182, 95, 3)', WebkitTextStrokeColor: 'rgb(182, 95, 3)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                  <span style={{fontFamily: '\'Font Awesome 6 Pro Light\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}></span>
                                                </span>
                                              </i>
                                            </div>
                                            <div className="ml-16" style={{marginLeft: '16px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 0px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="font-weight-600 font-18 focus-outline-border text-underline orange-foreground ng-star-inserted" style={{borderColor: 'rgb(182, 95, 3)', color: 'rgb(182, 95, 3)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '18px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '25.2px', outlineColor: 'rgb(182, 95, 3)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(182, 95, 3)', WebkitTextStrokeColor: 'rgb(182, 95, 3)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Compliance Management</span>
                                              </span>
                                            </div>
                                          </div>
                                          <div className="mt-8" style={{marginTop: '8px', alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '8px 0px 0px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="dashboard_nav_item_desc" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Review compliance documents setup for the programs of this</span>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>institution.</span>
                                              </span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </mat-card>
                                </div>
                                <div className="dashboard-screen-card-height pl-gt-sm-8 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '100%', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', maxWidth: '33.3333%', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '0px 0px 0px 8px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                  <mat-card className="mat-mdc-card mdc-card p-0 mb-lt-md-16 dashboard_card dashboard-screen-card-height teal-border ng-star-inserted" style={{backgroundColor: 'rgb(255, 255, 255)', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgb(3, 161, 160)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', borderWidth: '1px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexBasis: '0%', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', minHeight: '100%', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'relative', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '1', flexShrink: '1', opacity: '1'}}>
                                    <div className="card_content p-16 ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                      <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <div className="hover py-12 px-16 border-radius-8 cursor-pointer dashboard_nav_item ng-star-inserted" style={{alignContent: 'stretch', alignItems: 'stretch', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '12px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                          <div style={{alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <i className="fa-building fa-light s-24 teal-foreground" style={{width: '24px', height: '24px', borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline-block', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', minHeight: '24px', minWidth: '24px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span className="__h2d-remove-before __h2d-remove-after" style={{transformOrigin: '0px 0px', borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', textDecoration: 'rgb(13, 130, 130)', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                  <span style={{fontFamily: '\'Font Awesome 6 Pro Light\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}></span>
                                                </span>
                                              </i>
                                            </div>
                                            <div className="ml-16" style={{marginLeft: '16px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 0px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="font-weight-600 font-18 focus-outline-border text-underline teal-foreground ng-star-inserted" style={{borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '18px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '25.2px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Contracts &amp; Sites Management</span>
                                              </span>
                                            </div>
                                          </div>
                                          <div className="mt-8" style={{marginTop: '8px', alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '8px 0px 0px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="dashboard_nav_item_desc" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Find contact information, contracts, availability and clearance</span>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>requirements for clinical sites.</span>
                                              </span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                        <div className="hover py-12 px-16 border-radius-8 cursor-pointer dashboard_nav_item ng-star-inserted" style={{alignContent: 'stretch', alignItems: 'stretch', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderColor: 'rgba(0, 0, 0, 0.87)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', flexDirection: 'column', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', padding: '12px 16px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                          <div style={{alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div className="ng-star-inserted" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <i className="fa-hospital-user fa-light s-24 teal-foreground" style={{width: '24px', height: '24px', borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline-block', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', minHeight: '24px', minWidth: '24px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span className="__h2d-remove-before __h2d-remove-after" style={{transformOrigin: '0px 0px', borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline', fontFamily: '"Font Awesome 6 Pro"', fontSize: '24px', fontFeatureSettings: '"liga"', fontWeight: '300', lineHeight: '24px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', textDecoration: 'rgb(13, 130, 130)', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                  <span style={{fontFamily: '\'Font Awesome 6 Pro Light\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}></span>
                                                </span>
                                              </i>
                                            </div>
                                            <div className="ml-16" style={{marginLeft: '16px', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '0px 0px 0px 16px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="font-weight-600 font-18 focus-outline-border text-underline teal-foreground ng-star-inserted" style={{borderColor: 'rgb(13, 130, 130)', color: 'rgb(13, 130, 130)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '18px', fontWeight: '600', letterSpacing: '-0.1px', lineHeight: '25.2px', outlineColor: 'rgb(13, 130, 130)', outlineWidth: '3px', WebkitTextFillColor: 'rgb(13, 130, 130)', WebkitTextStrokeColor: 'rgb(13, 130, 130)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>Placement Report</span>
                                              </span>
                                            </div>
                                          </div>
                                          <div className="mt-8" style={{marginTop: '8px', alignContent: 'center', alignItems: 'center', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'flex', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', justifyContent: 'flex-start', letterSpacing: '-0.1px', lineHeight: '19.6px', margin: '8px 0px 0px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                              <span className="dashboard_nav_item_desc" style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'inline', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
                                                <span style={{fontFamily: '\'Source Sans Pro\', sans-serif', fontSize: '14px', whiteSpace: 'pre-wrap'}}>View consolidated placements report across programs.</span>
                                              </span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </mat-card>
                                </div>
                              </div>
                            </div>
                          </div>
                        </tenant-navigations>
                      </content>
                    </div>
                  </div>
                </div>
              </div>
            </vertical-layout-1>
          </v4-app-root>
          <div className="cdk-overlay-container" style={{width: '100%', height: '100%', borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', position: 'fixed', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', zIndex: '9999', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}}>
            <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
          </div>
          <div style={{borderColor: 'rgba(0, 0, 0, 0.87)', color: 'rgba(0, 0, 0, 0.87)', display: 'block', fontFamily: '"Source Sans Pro", sans-serif', fontSize: '14px', letterSpacing: '-0.1px', lineHeight: '19.6px', outlineColor: 'rgba(0, 0, 0, 0.87)', outlineWidth: '3px', WebkitTextFillColor: 'rgba(0, 0, 0, 0.87)', WebkitTextStrokeColor: 'rgba(0, 0, 0, 0.87)', order: '0', flexGrow: '0', flexShrink: '1', opacity: '1'}} />
        </body>
      </html>
      </div>
    </div>
  );
}

StepsExxatComAdminTenantApps1440WDefault.displayName = "Exxat - Tenant App";
